name: Auto VPS Extend

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run Script
        env:
          LABS_INSTANCE_NAME: ${{ secrets.LABS_INSTANCE_NAME }}
          DASHBOARD_TOKEN: ${{ secrets.DASHBOARD_TOKEN }}
          CF_CLEARANCE: ${{ secrets.CF_CLEARANCE }}
          BASE_URL: ${{ secrets.BASE_URL }}
          EXTEND_INTERVAL_MINUTES: ${{ secrets.EXTEND_INTERVAL_MINUTES }}
        run: python vps.py
